# Generated by Django 5.0.6 on 2026-05-15 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('employment_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract')], default='Full-time', max_length=20)),
                ('date_joined', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['country_code'], name='employees_e_country_cf4f51_idx'), models.Index(fields=['job_title'], name='employees_e_job_tit_cb57a0_idx'), models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx')],
            },
        ),
    ]
